//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.06 at 03:29:48 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.example/FlightOperations", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package example.com.flightoperations;
