
package trng.imcs.soap.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FlightsService", targetNamespace = "http://trng.imcs.soap/FlightsService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FlightsService {


    /**
     * 
     * @param parameters
     * @return
     *     returns trng.imcs.soap.stub.GetFlightsResponse
     */
    @WebMethod(action = "http://trng.imcs.soap/FlightsService/getFlights")
    @WebResult(name = "GetFlightsResponse", targetNamespace = "http://trng.imcs.soap/FlightOperations", partName = "parameters")
    public GetFlightsResponse getFlights(
        @WebParam(name = "GetFlightsRequest", targetNamespace = "http://trng.imcs.soap/FlightOperations", partName = "parameters")
        GetFlightsRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns trng.imcs.soap.stub.BookFlightResponse
     */
    @WebMethod(action = "http://trng.imcs.soap/FlightsService/bookFlights")
    @WebResult(name = "BookFlightResponse", targetNamespace = "http://trng.imcs.soap/FlightOperations", partName = "parameters")
    public BookFlightResponse bookFlights(
        @WebParam(name = "BookFlightRequest", targetNamespace = "http://trng.imcs.soap/FlightOperations", partName = "parameters")
        BookFlightRequest parameters);

}
