
package trng.imcs.soap.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderLibrary", targetNamespace = "http://www.example.org/OrderLibrary/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderLibrary {


    /**
     * 
     * @param parameters
     * @return
     *     returns trng.imcs.soap.stub.CreateCustomerResponse
     */
    @WebMethod(action = "http://www.example.org/NewWSDLFile/NewOperation")
    @WebResult(name = "createCustomerResponse", targetNamespace = "http://trng.imcs.wsdl/orderLibraryOperations", partName = "parameters")
    public CreateCustomerResponse createCustomer(
        @WebParam(name = "createCustomerRequest", targetNamespace = "http://trng.imcs.wsdl/orderLibraryOperations", partName = "parameters")
        CreateCustomerRequest parameters);

}
