
package trng.imcs.soap.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OrderLibrary", targetNamespace = "http://www.example.org/OrderLibrary/", wsdlLocation = "file:/D:/SWInstallation/IMCSWorkspace/WSDLGENERATION/src/main/resources/wsdl/OrderLibrary.wsdl")
public class OrderLibrary_Service
    extends Service
{

    private final static URL ORDERLIBRARY_WSDL_LOCATION;
    private final static WebServiceException ORDERLIBRARY_EXCEPTION;
    private final static QName ORDERLIBRARY_QNAME = new QName("http://www.example.org/OrderLibrary/", "OrderLibrary");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/SWInstallation/IMCSWorkspace/WSDLGENERATION/src/main/resources/wsdl/OrderLibrary.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ORDERLIBRARY_WSDL_LOCATION = url;
        ORDERLIBRARY_EXCEPTION = e;
    }

    public OrderLibrary_Service() {
        super(__getWsdlLocation(), ORDERLIBRARY_QNAME);
    }

    public OrderLibrary_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ORDERLIBRARY_QNAME, features);
    }

    public OrderLibrary_Service(URL wsdlLocation) {
        super(wsdlLocation, ORDERLIBRARY_QNAME);
    }

    public OrderLibrary_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ORDERLIBRARY_QNAME, features);
    }

    public OrderLibrary_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrderLibrary_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrderLibrary
     */
    @WebEndpoint(name = "OrderLibrarySOAP")
    public OrderLibrary getOrderLibrarySOAP() {
        return super.getPort(new QName("http://www.example.org/OrderLibrary/", "OrderLibrarySOAP"), OrderLibrary.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrderLibrary
     */
    @WebEndpoint(name = "OrderLibrarySOAP")
    public OrderLibrary getOrderLibrarySOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/OrderLibrary/", "OrderLibrarySOAP"), OrderLibrary.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ORDERLIBRARY_EXCEPTION!= null) {
            throw ORDERLIBRARY_EXCEPTION;
        }
        return ORDERLIBRARY_WSDL_LOCATION;
    }

}
